name = "Finalmc"
author = "jamdotjar"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f10c469861ae30ccdd877d7c73e3706cd8bdef72102a2a68b0ce1feaa64ed11d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.3"
