name = "Finalmc"
author = "jamdotjar"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00b22da36109e56c6e0b1196ef1d5afe27f193da1f9674b665be691b5c84745a"

[versions]
minecraft = "1.20.1"
quilt = "0.26.3"
