name = "Finalmc"
author = "jamdotjar"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4da1c941dc8f4676157eb1b11e9027caa1702edd8789bca7070993e6d52aba0f"

[versions]
minecraft = "1.20.1"
quilt = "0.26.3"
