name = "Finalmc"
author = "jamdotjar"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0369bf63fedd76bca03548ce4dafb5629eea76d5a7f45ab825f0f77ebd5951f5"

[versions]
minecraft = "1.20.1"
quilt = "0.26.3"
