name = "Finalmc"
author = "jamdotjar"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27274bf6e70d6233027537bebcb034047d302d85d1a523a2b4b5f0fb75c58f9f"

[versions]
minecraft = "1.20.1"
quilt = "0.26.3"
